### ISSUE TITLE
Can't connect to Jenkins HTTPS with self-signed certificate

### ISSUE THREAD

**Issue by whodafly** [gvalkov/jenkins-webapi#10]
I've set up a Jenkins instance over HTTPS with a self-signed certificate, and I cannot get jenkins-webapi to connect with the self-signed cert. The exception I'm getting is from the requests library, which does seem to support "ignoring" certificates. Is there a way jenkins-webapi could have an option to tell requests to ignore certificates?

Here's a simple example of an app:

```python
import sys
from jenkins import Jenkins, JenkinsError

token = sys.argv[1]
j = Jenkins('https://ci.openlp.io')
j.job('Trunk-01-Update').build(token=token)
```

And here's the exception I get:

```
@:~$ python3 jenkins_ssl.py
Traceback (most recent call last):
  File "/usr/lib/python3.4/site-packages/requests/packages/urllib3/connectionpool.py", line 544, in urlopen
    body=body, headers=headers)
  File "/usr/lib/python3.4/site-packages/requests/packages/urllib3/connectionpool.py", line 341, in _make_request
    self._validate_conn(conn)
  File "/usr/lib/python3.4/site-packages/requests/packages/urllib3/connectionpool.py", line 762, in _validate_conn
    conn.connect()
  File "/usr/lib/python3.4/site-packages/requests/packages/urllib3/connection.py", line 238, in connect
    ssl_version=resolved_ssl_version)
  File "/usr/lib/python3.4/site-packages/requests/packages/urllib3/util/ssl_.py", line 256, in ssl_wrap_socket
    return context.wrap_socket(sock, server_hostname=server_hostname)
  File "/usr/lib/python3.4/ssl.py", line 367, in wrap_socket
    _context=self)
  File "/usr/lib/python3.4/ssl.py", line 585, in __init__
    self.do_handshake()
  File "/usr/lib/python3.4/ssl.py", line 812, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:600)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.4/site-packages/requests/adapters.py", line 370, in send
    timeout=timeout
  File "/usr/lib/python3.4/site-packages/requests/packages/urllib3/connectionpool.py", line 574, in urlopen
    raise SSLError(e)
requests.packages.urllib3.exceptions.SSLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:600)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "jenkins_ssl.py", line 6, in <module>
    j.job('Trunk-01-Update').build(token=token)
  File "/usr/lib/python3.4/site-packages/jenkins.py", line 136, in build
    self._not_exist_raise()
  File "/usr/lib/python3.4/site-packages/jenkins.py", line 88, in _not_exist_raise
    if not self.exists:
  File "/usr/lib/python3.4/site-packages/jenkins.py", line 44, in exists
    self.info
  File "/usr/lib/python3.4/site-packages/jenkins.py", line 38, in info
    return self.server.json(url, errmsg=err)
  File "/usr/lib/python3.4/site-packages/jenkins.py", line 468, in json
    res = requests.get(url, auth=self.auth, **kw)
  File "/usr/lib/python3.4/site-packages/requests/api.py", line 65, in get
    return request('get', url, **kwargs)
  File "/usr/lib/python3.4/site-packages/requests/api.py", line 49, in request
    response = session.request(method=method, url=url, **kwargs)
  File "/usr/lib/python3.4/site-packages/requests/sessions.py", line 461, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python3.4/site-packages/requests/sessions.py", line 573, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python3.4/site-packages/requests/adapters.py", line 431, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:600)
```

**Comment by gvalkov** [comment]
Thank you for reporting this. I've exposed the `verify` and `cert` options as arguments to the `Jenkins` class in debfcecc3edcad185746655d67383675ca3a6d87. 

```python
>>> j = Jenkins('https://ci.openlp.io', verify=False)
>>> j.jobs
[Job(u'Branch-01-Pull'),
 Job(u'Branch-02-Functional-Tests'),
 ...
]
```

Feel free to upgrade to jenkins-webapi 0.4.1.

**Comment by whodafly** [comment]
Thank you!

**Comment by Huang-Jack** [comment]
Hi ,
I installed lastest jenkins package = 1.4.0, but I can not set the verify keyword to ignore https verificaiton
TypeError: __init__() got an unexpected keyword argument 'verify'

**Comment by JuliaTatarenkova** [comment]
You need to add to your script:

os.environ['PYTHONHTTPSVERIFY'] = "0"
