### ISSUE TITLE
It can't handle gzip'd responses

### ISSUE THREAD

**Issue by PaulKlumpp** [gvalkov/jenkins-webapi#11]
When cleaning up with jenkins-autojobs, it seems to have failed on the request's response:

```
processing branch: java/zoe-utils-jc/trunk
. job name: java_zoe-utils-jc_trunk
. job exists: True
. job does not need to be reconfigured
. job already in view: JobsManagedByAutojobs

cleaning up old jobs:
Traceback (most recent call last):
  File "/usr/bin/jenkins-makejobs-svn", line 9, in <module>
    load_entry_point('jenkins-autojobs==0.15.1', 'console_scripts', 'jenkins-makejobs-svn')()
  File "/usr/lib/python2.6/site-packages/jenkins_autojobs/svn.py", line 128, in main
    _main(argv[1:], config=config, create_job=create_job, list_branches=list_branches)
  File "/usr/lib/python2.6/site-packages/jenkins_autojobs/main.py", line 170, in main
    cleanup(config, job_names, jenkins)
  File "/usr/lib/python2.6/site-packages/jenkins_autojobs/main.py", line 193, in cleanup
    job.delete()
  File "/usr/lib/python2.6/site-packages/jenkins.py", line 117, in delete
    res = self.server.post(url, throw=False)
  File "/usr/lib/python2.6/site-packages/jenkins.py", line 466, in post
    res = requests.post(self.urljoin(url), **kw)
  File "/usr/lib/python2.6/site-packages/requests/api.py", line 109, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "/usr/lib/python2.6/site-packages/requests/api.py", line 50, in request
    response = session.request(method=method, url=url, **kwargs)
  File "/usr/lib/python2.6/site-packages/requests/sessions.py", line 465, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python2.6/site-packages/requests/sessions.py", line 605, in send
    r.content
  File "/usr/lib/python2.6/site-packages/requests/models.py", line 750, in content
    self._content = bytes().join(self.iter_content(CONTENT_CHUNK_SIZE)) or bytes()
  File "/usr/lib/python2.6/site-packages/requests/models.py", line 678, in generate
    raise ContentDecodingError(e)
requests.exceptions.ContentDecodingError: ('Received response with content-encoding: gzip, but failed to decode it.', error('Error -3 while decompressing: incorrect header check',))
```

I had a look at the source and googled the exception.

It seems we accept a gzip response in the request, but we actually can't handle and decode it. 
http://www.mobify.com/blog/http-requests-are-hard/
https://rationalpie.wordpress.com/2010/06/02/python-streaming-gzip-decompression/

Hm.

**Comment by gvalkov** [comment]
Hello. I'm trying to replicate the issue locally - could you provide the http debug log (`-t` flag)? 

One thing that might be worth trying as a workaround is to unset `Accept-Encoding`. You will have to download [jenkins.py](https://raw.githubusercontent.com/gvalkov/jenkins-webapi/master/jenkins.py) and apply this patch:

```diff
diff --git i/jenkins.py w/jenkins.py
index fb62af3..18cf1f0 100644
--- i/jenkins.py
+++ w/jenkins.py
@@ -452,6 +452,7 @@ class Server(object):
             'auth': self.auth,
             'cert': cert,
             'verify': verify,
+            'headers': {'Accept-Encoding': None},
         }
 
     def __repr__(self):
```

You can then run `PYTHONPATH=/path/to/dir/containing/jenkins.py jenkins-makejobs-svn -t config.yaml`.

**Comment by PaulKlumpp** [comment]
Also, I can't re-produce it on my home-machines. I made a virtualenv with Python 2.6.8 and pip install'd jenkins-autojobs there.
```
which jenkins-makejobs-git
/home/paul/storage1/dev/virtualenv_python/bin/jenkins-makejobs-git
```

```
cat /home/paul/storage1/dev/virtualenv_python/bin/jenkins-makejobs-git
#!/home/paul/storage1/dev/virtualenv_python/bin/python2.6

# -*- coding: utf-8 -*-
import re
import sys

from jenkins_autojobs.git import main

if __name__ == '__main__':
    sys.argv[0] = re.sub(r'(-script\.pyw|\.exe)?$', '', sys.argv[0])
    sys.exit(main())
```

```
git branch anotherone
```

```
jenkins-makejobs-git git-config.yaml

loading config from "/home/paul/storage1/dev/git/git-config.yaml"

processing ref: refs/heads/anotherone
. job name: anotherone
. job exists: False
. job created
. job added to view: view-name

processing ref: refs/heads/master
. job name: master
. job exists: True
. job does not need to be reconfigured
. job already in view: view-name

cleaning up old jobs:
. nothing to do
```

```
git branch -d anotherone
Deleted branch anotherone (was 16230eb).
```

```
jenkins-makejobs-git git-config.yaml
loading config from "/home/paul/storage1/dev/git/git-config.yaml"

processing ref: refs/heads/master
. job name: master
. job exists: True
. job does not need to be reconfigured
. job already in view: view-name

cleaning up old jobs:
 - anotherone
```

The version I have installed does not even have the "output=output" python6 fix.
For some reason, it all works. Now I think, I got my virtualenv wrong. But .. how? I will have to re-produce it on my work-machines in the office. And then I'll try 

```
'headers': {'Accept-Encoding': None},
```

**Comment by PaulKlumpp** [comment]
First, the debug output:

```
cleaning up old jobs:
send: 'GET /jenkins/api/json HTTP/1.1\r\nHost: soa-build-01.lxdev.ka.de.dm-drogeriemarkt.com:8080\r\nConnection: keep-alive\r\nAccept: */*\r\nAccept-Encoding: gzip, deflate\r\nAuthorization: Basic R<strippedaway>Q=\r\nUser-Agent: python-requests/2.7.0 CPython/2.6.6 Linux/2.6.32-358.el6.x86_64\r\n\r\n'
reply: 'HTTP/1.1 200 OK\r\n'
header: Server: Apache-Coyote/1.1^M
header: Cache-Control: private^M
header: Expires: Thu, 01 Jan 1970 01:00:00 CET^M
header: X-Jenkins: 1.578^M
header: X-Jenkins-Session: 61787708^M
header: Content-Encoding: gzip^M
header: Content-Type: application/json;charset=UTF-8^M
header: Content-Length: 2292^M
header: Date: Mon, 22 Jun 2015 09:00:30 GMT^M
send: 'GET /jenkins/job/bw-bc_dev-dummy-bc_branches_1.0.x/api/json?depth=0 HTTP/1.1\r\nHost: soa-build-01.lxdev.ka.de.dm-drogeriemarkt.com:8080\r\nConnection: keep-alive\r\nAccept: */*\r\nAccept-Encoding: gzip, deflate\r\nAuthorization: Basic R<strippedaway>Q=\r\nUser-Agent: python-requests/2.7.0 CPython/2.6.6 Linux/2.6.32-358.el6.x86_64\r\n\r\n'
reply: 'HTTP/1.1 200 OK\r\n'
header: Server: Apache-Coyote/1.1^M
header: Cache-Control: private^M
header: Expires: Thu, 01 Jan 1970 01:00:00 CET^M
header: X-Jenkins: 1.578^M
header: X-Jenkins-Session: 61787708^M
header: Content-Encoding: gzip^M
header: Content-Type: application/json;charset=UTF-8^M
header: Content-Length: 557^M
header: Date: Mon, 22 Jun 2015 09:01:20 GMT^M
send: 'POST /jenkins/job/bw-bc_dev-dummy-bc_branches_1.0.x/doDelete HTTP/1.1\r\nHost: soa-build-01.lxdev.ka.de.dm-drogeriemarkt.com:8080\r\nContent-Length: 0\r\nAccept-Encoding: gzip, deflate\r\nAccept: */*\r\nUser-Agent: python-requests/2.7.0 CPython/2.6.6 Linux/2.6.32-358.el6.x86_64\r\nConnection: keep-alive\r\nAuthorization: Basic R<strippedaway>Q=\r\n\r\n'
reply: 'HTTP/1.1 500 Internal Server Error\r\n'
header: Server: Apache-Coyote/1.1^M
header: Location: http://soa-build-01.lxdev.ka.de.dm-drogeriemarkt.com:8080/jenkins/^M
header: Content-Encoding: gzip^M
header: Expires: 0^M
header: Cache-Control: no-cache,no-store,must-revalidate^M
header: X-Hudson-Theme: default^M
header: X-Frame-Options: sameorigin^M
header: Set-Cookie: JSESSIONID=D6F5EFA136B20018DFF842EC9E27B2CA.cc4d163b21f48aca0216bf0f863132c6; Path=/jenkins/; HttpOnly^M
header: X-Hudson: 1.395^M
header: X-Jenkins: 1.578^M
header: X-Jenkins-Session: 61787708^M
header: X-Hudson-CLI-Port: 42619^M
header: X-Jenkins-CLI-Port: 42619^M
header: X-Jenkins-CLI2-Port: 42619^M
header: X-Instance-Identity: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAs47/jXNsXR4XhAuOibvIUHGk18bRh3mdh8o1wXQpAQnG9SB5wHXI5z4YQXoclAgB3fZTqmuYo7EOV4eQU+aP3x1QTbe9TbTA+IDAsjpkCF0BYjCSXx7BIG+X1hKsvWLhikKc9Tkk0NvMqK39Vbsm4lnGMS+Tk+diXDwAJPYA7+2oia2u2Tf7bAZmBcqt0zzDgyEM2gAqIiTPJyAv6XNRhvubMx5TAyjESxrVl5LLvkZ0ZryvGH92CsjFzD4oW8kUbP9jZhF/Q/gE3IkWIF2eTiIOfM3uQEfKLWJFqGJ6MO13Eg5DBHAhS70RPblI5fjZqtf0WOxYF4z+rVLPagL5mwIDAQAB^M
header: X-SSH-Endpoint: soa-build-01.lxdev.ka.de.dm-drogeriemarkt.com:55212^M
header: Content-Type: text/html;charset=UTF-8^M
header: Transfer-Encoding: chunked^M
header: Date: Mon, 22 Jun 2015 09:01:21 GMT^M
header: Connection: close^M
```

```
DEBUG:requests.packages.urllib3.connectionpool:"POST /jenkins/job/bw-bc_dev-dummy-bc_branches_1.0.x/doDelete HTTP/1.1" 500 None
Traceback (most recent call last):
  File "/usr/bin/jenkins-makejobs-svn", line 9, in <module>
    load_entry_point('jenkins-autojobs==0.15.1', 'console_scripts', 'jenkins-makejobs-svn')()
  File "/usr/lib/python2.6/site-packages/jenkins_autojobs/svn.py", line 128, in main
    _main(argv[1:], config=config, create_job=create_job, list_branches=list_branches)
  File "/usr/lib/python2.6/site-packages/jenkins_autojobs/main.py", line 170, in main
    cleanup(config, job_names, jenkins)
  File "/usr/lib/python2.6/site-packages/jenkins_autojobs/main.py", line 193, in cleanup
    job.delete()
  File "/usr/lib/python2.6/site-packages/jenkins.py", line 117, in delete
    res = self.server.post(url, throw=False, verify=False)
  File "/usr/lib/python2.6/site-packages/jenkins.py", line 467, in post
    res = requests.post(self.urljoin(url), **kw)
  File "/usr/lib/python2.6/site-packages/requests/api.py", line 109, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "/usr/lib/python2.6/site-packages/requests/api.py", line 50, in request
    response = session.request(method=method, url=url, **kwargs)
  File "/usr/lib/python2.6/site-packages/requests/sessions.py", line 465, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python2.6/site-packages/requests/sessions.py", line 605, in send
    r.content
  File "/usr/lib/python2.6/site-packages/requests/models.py", line 750, in content
    self._content = bytes().join(self.iter_content(CONTENT_CHUNK_SIZE)) or bytes()
  File "/usr/lib/python2.6/site-packages/requests/models.py", line 678, in generate
    raise ContentDecodingError(e)
requests.exceptions.ContentDecodingError: ('Received response with content-encoding: gzip, but failed to decode it.', error('Error -3 while decompressing: incorrect header check',))
```

So, yea, we get a 500 Internal Server Error. Hm, might be a known bug of Jenkins (version 1.578).

**Comment by PaulKlumpp** [comment]
So, I updated to Jenkins 1.617 and now it just worked! Sorry for suspecting a wrongful gzip-encoded-response.
But, at least we now know, if the thing dies with a internal server error (500) it might be Jenkins' problem.
