### ISSUE TITLE
Support for jobs in folders

### ISSUE THREAD

**Issue by sschwarzer** [gvalkov/jenkins-webapi#5]
Hello, thanks for your library. :-)

This issue is for jenkins-webapi version 0.3.0.

When I tried to create a new job inside a folder (created with the Cloudbees Folder Plugin, https://wiki.jenkins-ci.org/display/JENKINS/CloudBees+Folders+Plugin ) with

`job2 = server.job_create("TestFolder/TestJob2", job_config)`

(where `server` is a `Jenkins` instance and `job.config` is the XML configuration of an already existing job) I got the following traceback:

```
Traceback (most recent call last):
  File "D2SG/jenkins/jenkins_webapi_test.py", line 27, in <module>
    main()
  File "D2SG/jenkins/jenkins_webapi_test.py", line 23, in main
    job2 = server.job_create("TestFolder/TestJob2", job_config)
  File "/home/schwste/lib/python/jenkins.py", line 436, in job_create
    return Job.create(name, config, self.server)
  File "/home/schwste/lib/python/jenkins.py", line 158, in create
    raise JenkinsError('create "%s" failed' % name)
jenkins.JenkinsError: create "TestFolder/TestJob2" failed
```

It seems that the library tries to use `/createItem?name=TestFolder/TestJob2` as the URL path instead of `/job/TestFolder?createItem?name=TestJob2`.

Stefan

**Comment by KimonHoffmann** [comment]
Well I'm a bit late to the party, but I want to note that the suggested workaround does not work for Jenkins instances that are configured with CSRF protection enabled, because unfortunately it is not possible to request the crumb on the folder level.
